export const services = [
  // Agentic SEO remains the lead service; automation and apps support business operations.
  {slug:'agentic-seo',name:'Agentic SEO',summary:'Turn search opportunities into a focused plan—and a practical route from research to implementation.',body:'Search performance starts with understanding what customers need. I use Codex to support research, analysis and implementation, while personally reviewing every priority and deliverable so you know what matters and what happens next.',items:['Technical and on-page SEO review','Search intent and competitor research','Content planning and internal linking','Implementation priorities and measurement']},
  {slug:'local-seo',name:'Local SEO',summary:'Help nearby customers find your services, understand the fit and take the next step.',body:'Connect your website, service areas and business information so nearby customers can understand what you offer and find a clear path to contact you.',items:['Google Business Profile review','Service and location page planning','Local search intent research','Business information consistency']},
  {slug:'website-content',name:'Website Content Creation',summary:'Give prospects clear answers that build confidence and guide them towards an enquiry.',body:'Turn real customer questions into useful service pages and supporting content that makes your expertise easier to understand and the next step easier to take.',items:['Content briefs and research','Service page copy','Content refreshes','Editorial review and internal links']},
  {slug:'custom-websites',name:'Custom Websites',summary:'Create a fast, responsive website that makes your offer easier to understand and act on.',body:'Build purposeful pages around your audience, with clear content, responsive layouts, sound SEO foundations and a direct route to an enquiry.',items:['Custom landing pages','Responsive website development','SEO foundations','Launch and handover']},
  {slug:'business-automation',name:'Business Automation',summary:'Connect repetitive tasks into reliable workflows so your team can spend less time moving information by hand.',body:'Streamline everyday work with practical automations for enquiry handoffs, task reminders, data updates and reporting. We start with one clear process, agree where human approval is needed and test it before it touches live work.',items:['Workflow review and mapping','Tool and data connections','Approvals and exception handling','Testing, documentation and handover']},
  {slug:'basic-app-development',name:'Basic App Development',summary:'Turn a focused business need into a simple web app your team can use.',body:'Build small, purpose-built web apps such as internal task trackers, request forms, calculators and simple dashboards. We define the essential features first, then build and test a manageable tool around your team’s workflow.',items:['Requirements and prototype','Small web app development','Data and access planning','Testing and handover']},
  {slug:'growth-support',name:'Growth Support',summary:'Keep priority website and operational work moving with support scoped around your business.',body:'Get focused help with the website and operational tasks competing for your time, including custom WordPress pages, content updates and virtual assistance. Where a repeatable task is a good fit for automation, we can scope that separately and keep people focused on work that needs judgment.',items:['Custom WordPress pages','Website content updates','Research and administrative support','Ongoing tasks scoped together']}
];
export const projects = [
 {slug:'antons-plumbing',name:'Antons Plumbing & Gas',domain:'antonsplumbingandgas.com.au',industry:'Plumbing & trades',symbol:'AP',color:'mint'},
 {slug:'antons-renovations',name:'Antons Renovations',domain:'antonsrenovations.com.au',industry:'Renovations',symbol:'AR',color:'gold'}
];
