export const services = [
  {slug:'agentic-seo',name:'Agentic SEO',summary:'Turn search opportunities into a focused plan—and a practical route from research to implementation.',body:'Search performance starts with understanding what customers need. I use Codex to support research, analysis and implementation, while personally reviewing every priority and deliverable so you know what matters and what happens next.',items:['Technical and on-page SEO review','Search intent and competitor research','Content planning and internal linking','Implementation priorities and measurement']},
  {slug:'local-seo',name:'Local SEO',summary:'Help nearby customers find your services, understand the fit and take the next step.',body:'Connect your website, service areas and business information so nearby customers can understand what you offer and find a clear path to contact you.',items:['Google Business Profile review','Service and location page planning','Local search intent research','Business information consistency']},
  {slug:'website-content',name:'Website Content Creation',summary:'Give prospects clear answers that build confidence and guide them towards an enquiry.',body:'Turn real customer questions into useful service pages and supporting content that makes your expertise easier to understand and the next step easier to take.',items:['Content briefs and research','Service page copy','Content refreshes','Editorial review and internal links']},
  {slug:'custom-websites',name:'Custom Websites',summary:'Create a fast, responsive website that makes your offer easier to understand and act on.',body:'Build purposeful pages around your audience, with clear content, responsive layouts, sound SEO foundations and a direct route to an enquiry.',items:['Custom landing pages','Responsive website development','SEO foundations','Launch and handover']},
  {slug:'growth-support',name:'Growth Support',summary:'Keep priority website and operational work moving with support scoped around your business.',body:'Get focused help with the website and operational tasks competing for your time, including custom WordPress pages, content updates and virtual assistance.',items:['Custom WordPress pages','Website content updates','Research and administrative support','Ongoing tasks scoped together']}
];
export const projects = [
 {slug:'dayjob',name:'Dayjob.com.au',domain:'dayjob.com.au',industry:'Recruitment',symbol:'DJ',color:'blue'},
 {slug:'antons-plumbing',name:'Antons Plumbing & Gas',domain:'antonsplumbingandgas.com.au',industry:'Plumbing & trades',symbol:'AP',color:'mint'},
 {slug:'antons-renovations',name:'Antons Renovations',domain:'antonsrenovations.com.au',industry:'Renovations',symbol:'AR',color:'gold'},
 {slug:'christies-real-estate',name:'Christie’s Real Estate, Puerto Rico',domain:null,industry:'Real estate',symbol:'CR',color:'blue'}
];
